/**
 * Custom Monaco theme built from the frozen Transverse design tokens
 * (`src/app/theme.css`, plan.md §1.1). Monaco's theming API only accepts
 * literal hex/rgba strings — it has no notion of CSS custom properties —
 * so this is the one place in FORGE's owned paths a raw hex is expected
 * per the brief ("never a raw hex outside the Monaco theme definition").
 * Every value below is transcribed verbatim from `theme.css`; if that file
 * changes, update this one in the same PR.
 */
import type { editor } from "monaco-editor";

export const TRANSVERSE_THEME_NAME = "transverse-dark";

export const TRANSVERSE_MONACO_THEME: editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "comment", foreground: "6B7785", fontStyle: "italic" },
    { token: "comment.doc", foreground: "6B7785", fontStyle: "italic" },
    { token: "keyword", foreground: "00F2FF" },
    { token: "keyword.control", foreground: "00F2FF" },
    { token: "keyword.operator", foreground: "B9CACB" },
    { token: "string", foreground: "FFD166" },
    { token: "string.escape", foreground: "FFD166", fontStyle: "bold" },
    { token: "number", foreground: "00FFFF" },
    { token: "number.hex", foreground: "00FFFF" },
    { token: "type", foreground: "7DD3FC" },
    { token: "type.identifier", foreground: "7DD3FC" },
    { token: "identifier", foreground: "E2E2E8" },
    { token: "delimiter", foreground: "B9CACB" },
    { token: "delimiter.bracket", foreground: "B9CACB" },
    { token: "operator", foreground: "B9CACB" },
    { token: "variable", foreground: "E2E2E8" },
    { token: "variable.predefined", foreground: "FF6B6B" },
    { token: "constant", foreground: "00FFFF" },
    { token: "annotation", foreground: "FF6B6B" },
    { token: "tag", foreground: "00F2FF" },
    { token: "attribute.name", foreground: "7DD3FC" },
    { token: "attribute.value", foreground: "FFD166" },
  ],
  colors: {
    "editor.background": "#0A0A12",
    "editor.foreground": "#E2E2E8",
    "editorLineNumber.foreground": "#3A494B",
    "editorLineNumber.activeForeground": "#00F2FF",
    "editorCursor.foreground": "#00F2FF",
    "editor.selectionBackground": "#0E4249",
    "editor.selectionHighlightBackground": "#00F2FF26",
    "editor.inactiveSelectionBackground": "#0E424980",
    "editor.wordHighlightBackground": "#00F2FF1A",
    "editor.wordHighlightStrongBackground": "#00F2FF2E",
    "editor.findMatchBackground": "#FFD16655",
    "editor.findMatchHighlightBackground": "#FFD16633",
    "editor.lineHighlightBackground": "#161B22",
    "editor.lineHighlightBorder": "#30363D",
    "editorGutter.background": "#0A0A12",
    "editorIndentGuide.background1": "#30363D",
    "editorIndentGuide.activeBackground1": "#00F2FF66",
    "editorWhitespace.foreground": "#30363D",
    "editorWidget.background": "#161B22",
    "editorWidget.foreground": "#E2E2E8",
    "editorWidget.border": "#30363D",
    "editorSuggestWidget.background": "#161B22",
    "editorSuggestWidget.border": "#30363D",
    "editorSuggestWidget.selectedBackground": "#282A2E",
    "editorSuggestWidget.highlightForeground": "#00F2FF",
    "editorHoverWidget.background": "#161B22",
    "editorHoverWidget.border": "#30363D",
    "scrollbarSlider.background": "#30363D80",
    "scrollbarSlider.hoverBackground": "#3A494B99",
    "scrollbarSlider.activeBackground": "#00F2FF55",
    "editorBracketMatch.background": "#00F2FF22",
    "editorBracketMatch.border": "#00F2FF88",
    "editorBracketHighlight.foreground1": "#00F2FF",
    "editorBracketHighlight.foreground2": "#FFD166",
    "editorBracketHighlight.foreground3": "#FF6B6B",
    "minimap.background": "#0A0A12",
    "minimapSlider.background": "#30363D66",
    "editorError.foreground": "#FF6B6B",
    "editorWarning.foreground": "#FFD166",
    "editorInfo.foreground": "#00F2FF",
    "editorGutter.addedBackground": "#00F2FF",
    "editorGutter.modifiedBackground": "#FFD166",
    "editorGutter.deletedBackground": "#FF6B6B",
    "diffEditor.insertedTextBackground": "#00F2FF22",
    "diffEditor.removedTextBackground": "#FF6B6B22",
    "input.background": "#161B22",
    "input.border": "#30363D",
    "input.foreground": "#E2E2E8",
    focusBorder: "#00F2FF88",
    "dropdown.background": "#161B22",
    "dropdown.border": "#30363D",
    "panel.border": "#30363D",
  },
};
